package main

import (
	"errors"
	"fmt"
	"net"
	"net/url"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

// Every string that ends up in a file name or inside a Caddyfile passes through
// this file first. Nothing here trusts the caller.

const (
	// MaxUploadSize is the hard per-file limit for uploads (50 MB).
	MaxUploadSize = 50 << 20
	// MaxLabelLen bounds whitelist labels.
	MaxLabelLen = 40
	// MaxObjectKeyLen is the S3 limit for object keys.
	MaxObjectKeyLen = 1024
	// MaxFolderNameLen bounds one path component of a key (S3 keys are
	// otherwise free-form; 255 bytes matches every file system).
	MaxFolderNameLen = 255
	// MaxTransfers caps the parallel transfers one sync job may ask rclone
	// for.
	MaxTransfers = 16
)

var (
	// Bucket names: 3..63 chars, lowercase alphanumeric and dashes, no leading
	// or trailing dash.
	bucketNameRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$`)

	// Domains: lowercase labels separated by dots, at least two labels.
	domainRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$`)

	// Labels for whitelist entries. The pipe character is deliberately excluded
	// because it separates value from label in the Caddyfile comment.
	labelRe = regexp.MustCompile(`^[a-zA-Z0-9 _-]+$`)

	// Remote names: short, lowercase, safe as a map key, a JSON value and a
	// file-name component.
	remoteNameRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,31}$`)
	// Regions as every provider spells them (us-east-1, ap-southeast-1,
	// garage).
	regionRe = regexp.MustCompile(`^[a-z0-9-]{1,32}$`)
	// Bucket names on other providers follow the AWS rule, which allows dots.
	remoteBucketRe = regexp.MustCompile(`^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$`)
	ipv4LikeRe     = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$`)
	// Job ids are generated by the panel (8 random bytes, hex).
	jobIDRe = regexp.MustCompile(`^[0-9a-f]{16}$`)
	// One DNS label.
	dnsLabelRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)
)

// remoteProviders is the rclone "provider" whitelist offered in the UI.
var remoteProviders = []string{"Wasabi", "AWS", "Minio", "Other"}

// syncModes are the ways a sync job treats objects that already exist at the
// destination.
var syncModes = map[string]string{
	"skip-existing":       "hanya salin objek yang belum ada di tujuan",
	"update-if-different": "salin objek yang belum ada atau ukurannya beda",
	"overwrite":           "salin semua objek, timpa yang ada",
}

// ValidateBucketName checks a bucket name before it is used in an API call, a
// Caddyfile body or a file name.
func ValidateBucketName(s string) error {
	if s == "" {
		return errors.New("nama bucket tidak boleh kosong")
	}
	if len(s) > 63 {
		return errors.New("nama bucket maksimal 63 karakter")
	}
	if !bucketNameRe.MatchString(s) {
		return fmt.Errorf("nama bucket %q tidak valid: gunakan 3-63 karakter huruf kecil, angka, dan tanda hubung; tidak boleh diawali/diakhiri tanda hubung", s)
	}
	// Defence in depth: the regexp already excludes these, but the value is
	// used as a path component so check explicitly.
	return SafeFilenameComponent(s, "nama bucket")
}

// ValidateDomain checks a domain before it is used as "<domain>.caddy" and as a
// site address inside a Caddyfile.
func ValidateDomain(s string) error {
	if s == "" {
		return errors.New("domain tidak boleh kosong")
	}
	if len(s) > 253 {
		return errors.New("domain maksimal 253 karakter")
	}
	if !domainRe.MatchString(s) {
		return fmt.Errorf("domain %q tidak valid: gunakan huruf kecil, angka, tanda hubung, dan minimal satu titik (contoh: cdn.example.com)", s)
	}
	return SafeFilenameComponent(s, "domain")
}

// ValidateIPOrCIDR parses an IP address or CIDR block and returns its canonical
// textual form. Parsing is done with net.ParseIP / net.ParseCIDR, never with a
// regexp, and the canonical form is what gets written to the Caddyfile.
func ValidateIPOrCIDR(s string) (string, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", errors.New("IP atau CIDR tidak boleh kosong")
	}
	if strings.Contains(s, "/") {
		_, ipnet, err := net.ParseCIDR(s)
		if err != nil {
			return "", fmt.Errorf("CIDR %q tidak valid: %v", s, err)
		}
		// ipnet.String() masks off host bits, so 198.51.100.5/24 becomes
		// 198.51.100.0/24.
		return ipnet.String(), nil
	}
	ip := net.ParseIP(s)
	if ip == nil {
		return "", fmt.Errorf("IP %q tidak valid", s)
	}
	return ip.String(), nil
}

// ValidateLabel checks a human label used in Caddyfile comments.
func ValidateLabel(s string) error {
	if s == "" {
		return errors.New("label tidak boleh kosong")
	}
	if utf8.RuneCountInString(s) > MaxLabelLen {
		return fmt.Errorf("label maksimal %d karakter", MaxLabelLen)
	}
	if !labelRe.MatchString(s) {
		return errors.New("label hanya boleh berisi huruf, angka, spasi, garis bawah, dan tanda hubung")
	}
	return nil
}

// ValidateObjectKey rejects keys that could escape the bucket or break the
// request line.
func ValidateObjectKey(s string) error {
	if s == "" {
		return errors.New("object key tidak boleh kosong")
	}
	if len(s) > MaxObjectKeyLen {
		return fmt.Errorf("object key maksimal %d karakter", MaxObjectKeyLen)
	}
	if strings.HasPrefix(s, "/") {
		return errors.New("object key tidak boleh diawali \"/\"")
	}
	// Dot segments are refused per path component, not by substring: a key
	// like "laporan..final.pdf" is legitimate on every provider, while
	// "../escape.jpg" and "a/../b" are not.
	for _, seg := range strings.Split(s, "/") {
		if seg == "." || seg == ".." {
			return errors.New("object key tidak boleh mengandung segmen \".\" atau \"..\"")
		}
	}
	if !utf8.ValidString(s) {
		return errors.New("object key bukan UTF-8 yang valid")
	}
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return errors.New("object key mengandung karakter kontrol")
		}
	}
	return nil
}

// ValidatePrefix checks a listing prefix. Same rules as a key, but empty is
// allowed (it means "bucket root").
func ValidatePrefix(s string) error {
	if s == "" {
		return nil
	}
	return ValidateObjectKey(s)
}

// SafeFilenameComponent rejects anything that must never be used as part of a
// file path: separators, dot segments, control characters and NUL.
func SafeFilenameComponent(s, what string) error {
	if s == "" || s == "." || s == ".." {
		return fmt.Errorf("%s tidak valid", what)
	}
	if strings.Contains(s, "..") {
		return fmt.Errorf("%s tidak boleh mengandung \"..\"", what)
	}
	if strings.ContainsAny(s, `/\`) {
		return fmt.Errorf("%s tidak boleh mengandung \"/\" atau \"\\\"", what)
	}
	if strings.HasPrefix(s, ".") {
		return fmt.Errorf("%s tidak boleh diawali titik", what)
	}
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("%s mengandung karakter kontrol", what)
		}
	}
	// The file name is built as "<component>.caddy"; keep it well below any
	// filesystem limit.
	if len(s) > 200 {
		return fmt.Errorf("%s terlalu panjang", what)
	}
	return nil
}

// allowedExtensions is the upload whitelist: extension -> content type.
// Anything not listed here is rejected.
var allowedExtensions = map[string]string{
	// raster images
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".png":  "image/png",
	".gif":  "image/gif",
	".webp": "image/webp",
	".avif": "image/avif",
	".bmp":  "image/bmp",
	".ico":  "image/x-icon",
	".tif":  "image/tiff",
	".tiff": "image/tiff",
	// vector / web assets
	".svg":  "image/svg+xml",
	".css":  "text/css; charset=utf-8",
	".js":   "text/javascript; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".htm":  "text/html; charset=utf-8",
	".map":  "application/json",
	// fonts
	".woff":  "font/woff",
	".woff2": "font/woff2",
	".ttf":   "font/ttf",
	".otf":   "font/otf",
	".eot":   "application/vnd.ms-fontobject",
	// documents
	".pdf":  "application/pdf",
	".txt":  "text/plain; charset=utf-8",
	".md":   "text/markdown; charset=utf-8",
	".csv":  "text/csv; charset=utf-8",
	".json": "application/json",
	".xml":  "application/xml",
	".yml":  "text/plain; charset=utf-8",
	".yaml": "text/plain; charset=utf-8",
	// media
	".mp4":  "video/mp4",
	".webm": "video/webm",
	".mov":  "video/quicktime",
	".mp3":  "audio/mpeg",
	".ogg":  "audio/ogg",
	".wav":  "audio/wav",
	".m4a":  "audio/mp4",
	// archives
	".zip": "application/zip",
	".gz":  "application/gzip",
	".tar": "application/x-tar",
	".7z":  "application/x-7z-compressed",
}

// imageExtensions are rendered as thumbnails in the grid and are the only
// content types the /preview endpoint will serve inline.
var imageExtensions = map[string]bool{
	".jpg":  true,
	".jpeg": true,
	".png":  true,
	".webp": true,
	".gif":  true,
	".avif": true,
}

// AllowedExtensionList returns the upload whitelist, sorted, for display.
func AllowedExtensionList() []string {
	out := make([]string, 0, len(allowedExtensions))
	for ext := range allowedExtensions {
		out = append(out, strings.TrimPrefix(ext, "."))
	}
	sort.Strings(out)
	return out
}

// ValidateUploadName checks the client-supplied file name and returns the
// lowercase extension (with leading dot) and its content type.
func ValidateUploadName(name string) (ext, contentType string, err error) {
	// Only the extension survives: the stored key is sha256(content)[:16]+ext.
	base := path.Base(strings.ReplaceAll(name, `\`, `/`))
	ext = strings.ToLower(path.Ext(base))
	if ext == "" {
		return "", "", fmt.Errorf("file %q tidak punya ekstensi", name)
	}
	ct, ok := allowedExtensions[ext]
	if !ok {
		return "", "", fmt.Errorf("ekstensi %q tidak diizinkan", ext)
	}
	return ext, ct, nil
}

// IsImageKey reports whether a key should be shown as a thumbnail.
func IsImageKey(key string) bool {
	return imageExtensions[strings.ToLower(path.Ext(key))]
}

// ContentTypeForKey returns the content type for a stored key, or the empty
// string when the extension is not on the whitelist.
func ContentTypeForKey(key string) string {
	return allowedExtensions[strings.ToLower(path.Ext(key))]
}

// --- sync: remotes and jobs ----------------------------------------------

// ValidateRemoteName checks the short name a remote is saved under.
func ValidateRemoteName(s string) error {
	if s == "" {
		return errors.New("nama remote tidak boleh kosong")
	}
	if !remoteNameRe.MatchString(s) {
		return fmt.Errorf("nama remote %q tidak valid: gunakan 1-32 karakter huruf kecil, angka, dan tanda hubung, diawali huruf/angka", s)
	}
	return SafeFilenameComponent(s, "nama remote")
}

// ValidateRemoteEndpoint checks an S3 endpoint URL and returns it normalised
// (lowercase host, no trailing slash).
//
// Only the origin is accepted — scheme, host and optional port. A path, query,
// fragment or user-info would let the panel be pointed at an arbitrary URL, so
// they are refused, as are link-local and unspecified addresses (the cloud
// metadata service lives on 169.254.169.254). Plain http stays allowed for a
// second Garage on the LAN; the UI marks it as unencrypted.
func ValidateRemoteEndpoint(s string) (string, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", errors.New("endpoint tidak boleh kosong")
	}
	if len(s) > 300 {
		return "", errors.New("endpoint terlalu panjang")
	}
	u, err := url.Parse(s)
	if err != nil {
		return "", fmt.Errorf("endpoint %q tidak valid: %v", s, err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return "", fmt.Errorf("endpoint harus diawali https:// atau http:// (dapat %q)", s)
	}
	if u.User != nil {
		return "", errors.New("endpoint tidak boleh memuat username/password — kredensial diisi di kolomnya sendiri")
	}
	if (u.Path != "" && u.Path != "/") || u.RawQuery != "" || u.Fragment != "" || u.Opaque != "" {
		return "", fmt.Errorf("endpoint hanya boleh berisi skema dan host, contoh https://s3.wasabisys.com (dapat %q)", s)
	}
	host := strings.ToLower(u.Hostname())
	if host == "" {
		return "", errors.New("endpoint tidak punya host")
	}
	if port := u.Port(); port != "" {
		n, err := strconv.Atoi(port)
		if err != nil || n < 1 || n > 65535 {
			return "", fmt.Errorf("port %q tidak valid", port)
		}
	}
	if ip := net.ParseIP(host); ip != nil {
		if ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() || ip.IsMulticast() || ip.IsUnspecified() {
			return "", fmt.Errorf("alamat %s tidak boleh dipakai sebagai endpoint", host)
		}
	} else {
		if len(host) > 253 {
			return "", errors.New("host endpoint terlalu panjang")
		}
		for _, label := range strings.Split(host, ".") {
			if !dnsLabelRe.MatchString(label) {
				return "", fmt.Errorf("host %q bukan nama DNS yang valid", host)
			}
		}
	}
	normalised := u.Scheme + "://" + host
	if u.Port() != "" {
		normalised += ":" + u.Port()
	}
	return normalised, nil
}

// ValidateRegion checks a SigV4 region name.
func ValidateRegion(s string) error {
	if s == "" {
		return errors.New("region tidak boleh kosong (Wasabi: us-east-1 untuk s3.wasabisys.com; Garage: nilai s3_region)")
	}
	if !regionRe.MatchString(s) {
		return fmt.Errorf("region %q tidak valid: huruf kecil, angka, dan tanda hubung saja", s)
	}
	return nil
}

// ValidateProvider checks the rclone provider name against the whitelist.
func ValidateProvider(s string) error {
	for _, p := range remoteProviders {
		if s == p {
			return nil
		}
	}
	return fmt.Errorf("provider %q tidak dikenal; pilih salah satu dari %s", s, strings.Join(remoteProviders, ", "))
}

// ValidateRemoteBucketName checks a bucket name on another provider. AWS
// allows dots, so this is looser than ValidateBucketName; the value is only
// ever used in a URL path and in JSON, never as a file name.
func ValidateRemoteBucketName(s string) error {
	if s == "" {
		return errors.New("nama bucket remote tidak boleh kosong")
	}
	if len(s) > 63 || !remoteBucketRe.MatchString(s) {
		return fmt.Errorf("nama bucket remote %q tidak valid: 3-63 karakter huruf kecil, angka, titik, dan tanda hubung", s)
	}
	if strings.Contains(s, "..") || strings.Contains(s, ".-") || strings.Contains(s, "-.") {
		return fmt.Errorf("nama bucket remote %q tidak valid: titik dan tanda hubung tidak boleh berdampingan", s)
	}
	if ipv4LikeRe.MatchString(s) {
		return fmt.Errorf("nama bucket remote %q tidak boleh berbentuk alamat IP", s)
	}
	return nil
}

// ValidateJobPrefix checks a sync/job prefix: empty means the whole bucket,
// anything else must end with "/" so keys stay relative to a folder.
func ValidateJobPrefix(s string) error {
	if s == "" {
		return nil
	}
	if err := ValidateObjectKey(s); err != nil {
		return fmt.Errorf("prefix: %w", err)
	}
	if !strings.HasSuffix(s, "/") {
		return fmt.Errorf("prefix %q harus diakhiri \"/\"", s)
	}
	return nil
}

// ValidateFolderName checks one path component typed by the user (a new
// folder, or the target of a rename).
func ValidateFolderName(s string) error {
	if s == "" {
		return errors.New("nama tidak boleh kosong")
	}
	if len(s) > MaxFolderNameLen {
		return fmt.Errorf("nama maksimal %d byte", MaxFolderNameLen)
	}
	if !utf8.ValidString(s) {
		return errors.New("nama bukan UTF-8 yang valid")
	}
	if s == "." || s == ".." {
		return errors.New("nama tidak boleh \".\" atau \"..\"")
	}
	if strings.ContainsAny(s, "/\\") {
		return errors.New("nama tidak boleh mengandung \"/\" atau \"\\\"")
	}
	if strings.TrimSpace(s) != s {
		return errors.New("nama tidak boleh diawali atau diakhiri spasi")
	}
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return errors.New("nama mengandung karakter kontrol")
		}
	}
	return nil
}

// ValidateObjectBaseName checks a file name that becomes the last component
// of a key (upload with the original name, rename) and returns its extension
// and content type from the upload whitelist.
func ValidateObjectBaseName(s string) (ext, contentType string, err error) {
	if err := ValidateFolderName(s); err != nil {
		return "", "", err
	}
	if strings.HasPrefix(s, ".") {
		return "", "", errors.New("nama tidak boleh diawali titik")
	}
	return ValidateUploadName(s)
}

// ValidateJobID checks an id before it is joined into a path under STATE_DIR.
func ValidateJobID(s string) error {
	if !jobIDRe.MatchString(s) {
		return fmt.Errorf("id job %q tidak valid", s)
	}
	return nil
}

// ValidateTransfers bounds the parallel transfers handed to rclone.
func ValidateTransfers(n int) error {
	if n < 1 || n > MaxTransfers {
		return fmt.Errorf("transfers harus antara 1 dan %d", MaxTransfers)
	}
	return nil
}

// ValidateSyncMode checks the "what about objects that already exist" choice.
func ValidateSyncMode(s string) error {
	if _, ok := syncModes[s]; !ok {
		return fmt.Errorf("mode %q tidak dikenal", s)
	}
	return nil
}

// SortParams whitelists the object-listing sort controls, falling back to
// name/ascending for anything unexpected.
func SortParams(sortBy, dir string) (string, string) {
	switch sortBy {
	case "name", "size", "date":
	default:
		sortBy = "name"
	}
	if dir != "desc" {
		dir = "asc"
	}
	return sortBy, dir
}
